version: '3'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      SA_PASSWORD: "Arkam2004"
      ACCEPT_EULA: "Y"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: arkam
      MINIO_ROOT_PASSWORD: Arkam2004
    command: server --console-address ":9001" /data

  meilisearch:
    image: getmeili/meilisearch
    restart: always
    ports:
      - 7700:7700
    volumes:
      - meilisearch_data:/data
    environment:
      MEILI_MASTER_KEY: Arkam2004
      MEILI_ENV: development
      MEILI_DB_PATH: /data

volumes:
  minio_data:
  meilisearch_data: