// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Bucket struct {
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type CreateBucketInput struct {
	Name          string `json:"name"`
	ObjectLocking bool   `json:"object_locking"`
}

type DeleteBucketInput struct {
	Name string `json:"name"`
}

type Error struct {
	Message string `json:"message"`
	Reason  string `json:"reason"`
}

type MetaData struct {
	AvailableBuckets []string `json:"AVAILABLE_BUCKETS"`
}

type Object struct {
	Name   string `json:"name"`
	Path   string `json:"path"`
	Bucket string `json:"bucket"`
}

type PresignedGetURLInput struct {
	ObjectName string `json:"object_name"`
	BucketName string `json:"bucket_name"`
}

type PresignedPutURLInput struct {
	ObjectName string `json:"object_name"`
	BucketName string `json:"bucket_name"`
}

type PresignedURL struct {
	ObjectName   string `json:"object_name"`
	URL          string `json:"url"`
	URLOperation string `json:"url_operation"`
	Host         string `json:"host"`
	Bucket       string `json:"bucket"`
	Path         string `json:"path"`
	Expiry       string `json:"expiry"`
}

type RemoveObjectInput struct {
	Name       string `json:"name"`
	BucketName string `json:"bucket_name"`
}

type Response struct {
	Message string `json:"message"`
}

type UploadObjectInput struct {
	Name       string         `json:"name"`
	BucketName string         `json:"bucket_name"`
	Object     graphql.Upload `json:"object"`
}
